// <auto-generated />
using System;
using AgenciaFinal.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgenciaFinal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210809205706_m6")]
    partial class m6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgenciaFinal.Models.Agencia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantAlojamientos")
                        .HasColumnType("int");

                    b.Property<int?>("id_alojamientoId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("id_alojamientoId");

                    b.ToTable("Agencia");
                });

            modelBuilder.Entity("AgenciaFinal.Models.Alojamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("barrio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cantidadDeBanios")
                        .HasColumnType("int");

                    b.Property<int>("cantidadDePersonas")
                        .HasColumnType("int");

                    b.Property<int>("cantidad_de_habitaciones")
                        .HasColumnType("int");

                    b.Property<string>("ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("esHotel")
                        .HasColumnType("bit");

                    b.Property<string>("estrellas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precio_por_dia")
                        .HasColumnType("float");

                    b.Property<double>("precio_por_persona")
                        .HasColumnType("float");

                    b.Property<bool>("tv")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Alojamiento");
                });

            modelBuilder.Entity("AgenciaFinal.Models.Ciudades", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("AgenciaFinal.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FHasta")
                        .HasColumnType("datetime2");

                    b.Property<float>("PDesde")
                        .HasColumnType("real");

                    b.Property<float>("Phasta")
                        .HasColumnType("real");

                    b.Property<int>("contador")
                        .HasColumnType("int");

                    b.Property<int?>("id_alojamientoId")
                        .HasColumnType("int");

                    b.Property<int?>("id_usuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_alojamientoId");

                    b.HasIndex("id_usuarioId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("AgenciaFinal.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("bit");

                    b.Property<int>("IntentosDeLogueos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuario", "dbo");
                });

            modelBuilder.Entity("AgenciaFinal.Models.Agencia", b =>
                {
                    b.HasOne("AgenciaFinal.Models.Alojamiento", "id_alojamiento")
                        .WithMany()
                        .HasForeignKey("id_alojamientoId");

                    b.Navigation("id_alojamiento");
                });

            modelBuilder.Entity("AgenciaFinal.Models.Reserva", b =>
                {
                    b.HasOne("AgenciaFinal.Models.Alojamiento", "id_alojamiento")
                        .WithMany()
                        .HasForeignKey("id_alojamientoId");

                    b.HasOne("AgenciaFinal.Models.Usuario", "id_usuario")
                        .WithMany()
                        .HasForeignKey("id_usuarioId");

                    b.Navigation("id_alojamiento");

                    b.Navigation("id_usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
